// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrWkxEgoF6UxEAoT7BtVvm4AC_w-H9T2Q',
    appId: '1:656699164639:web:174fdc0fcaaa04ac90a66a',
    messagingSenderId: '656699164639',
    projectId: 'nutritrack-33797',
    authDomain: 'nutritrack-33797.firebaseapp.com',
    storageBucket: 'nutritrack-33797.firebasestorage.app',
    measurementId: 'G-DNLVDWRL77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh22zk4BXEjQIPiuCzvRs3fpspAU5A1iY',
    appId: '1:656699164639:android:58870ae1b5525c4b90a66a',
    messagingSenderId: '656699164639',
    projectId: 'nutritrack-33797',
    storageBucket: 'nutritrack-33797.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjImmAufQ7ctpPRIL-UMMPljwpthQwxHQ',
    appId: '1:656699164639:ios:8f7271e38a511b9a90a66a',
    messagingSenderId: '656699164639',
    projectId: 'nutritrack-33797',
    storageBucket: 'nutritrack-33797.firebasestorage.app',
    iosBundleId: 'com.example.nutriTrack',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjImmAufQ7ctpPRIL-UMMPljwpthQwxHQ',
    appId: '1:656699164639:ios:8f7271e38a511b9a90a66a',
    messagingSenderId: '656699164639',
    projectId: 'nutritrack-33797',
    storageBucket: 'nutritrack-33797.firebasestorage.app',
    iosBundleId: 'com.example.nutriTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrWkxEgoF6UxEAoT7BtVvm4AC_w-H9T2Q',
    appId: '1:656699164639:web:ae9e1bccd1904e5990a66a',
    messagingSenderId: '656699164639',
    projectId: 'nutritrack-33797',
    authDomain: 'nutritrack-33797.firebaseapp.com',
    storageBucket: 'nutritrack-33797.firebasestorage.app',
    measurementId: 'G-RHRZ48JQF3',
  );
}
